language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 2.7

sudo: false

addons:
  apt:
    packages:
      - python-numpy

install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt

script:
  - make tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - openssl aes-256-cbc -K $encrypted_7585a52457ca_key -iv $encrypted_7585a52457ca_iv -in .pypirc.enc -out ~/.pypirc -d
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a $TRAVIS_PYTHON_VERSION == "2.7" -a -n "$(grep version setup.py | cut -d \' -f 2 | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$')" ]; then
      make publish;
    fi
  - if [ "$TRAVIS_BRANCH" = "beta" -a "$TRAVIS_PULL_REQUEST" = "false" -a $TRAVIS_PYTHON_VERSION == "2.7" -a -n "$(grep version setup.py | cut -d \' -f 2 | grep -E '^[0-9]+\.[0-9]+\.[0-9]+b[0-9]+$')" ]; then
      make publish;
    fi

notifications:
  slack: 3point:n4uGopqXrpbYFbslpV5z0tyO
  email: false
